#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

readonly URL=http://philsc.net/Build-Dependencies/bazel-incompatible-target-skipping-bazelcon2020-b
readonly SHASUM=fa5f45a5ffd88d1d7e044e3d37fb91c8c044a37e3ac5e8bbeddd197f74654edb

readonly TEMPFILE=/tmp/bazel-incompatible-target-skipping-bazelcon2020

if [[ ! -r "${TEMPFILE}" || "$(sha256sum "${TEMPFILE}")" != "${SHASUM}  ${TEMPFILE}" ]]; then
    curl -L "${URL}" > "${TEMPFILE}"
fi

chmod +x "${TEMPFILE}"

exec "${TEMPFILE}" "$@"
